version: "3.8"

services:
  app:
    container_name: app
    image: go-app:alpine
    restart: on-failure:8
    command: ./wait-for-postgres.sh db ./main
    ports:
      - "80:8080"
    environment:
      POSTGRES_PASSWORD: pass
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
