-- Active: 1669879880761@@91.220.109.55@5434@postgres
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (121,'Сервисмаркет на Черняховского') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (26928,'Сервисмаркет на Бебеля') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (26929,'Сервисмаркет на Онежской') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270069,'Сервисмаркет на Щорса') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270070,'Сервисмаркет на Высоцкого') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270071,'Сервисмаркет на Восточной') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270072,'Сервисмаркет на Осипенко') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270073,'Сервисмаркет на Учителей') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270074,'Сервисмаркет на Успенском проспекте') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270075,'Сервисмаркет 30 лет Победы') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270076,'Сервисмаркет на Онуфриева') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270077,'Сервисмаркет на Крауля') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270078,'Сервисмаркет на Репина') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270079,'Сервисмаркет на Черноисточинском шоссе') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270080,'Сервисмаркет на Малкова') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (270081,'Сервисмаркет на Чернышевского') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (427879,'Сервисмаркет на Шефской') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (799363,'Сервисмаркет на Айвазовского') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (816180,'Сервисмаркет на Крестинского') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (922644,'Сервисмаркет на Широтной') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (946545,'Сервисмаркет на Парижской коммуны') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (999547,'Сервисмаркет на Баязита Бикбая') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (1122418,'Сервисмаркет на Уфимском шоссе') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (1577682,'Сервисмаркет на Космонавтов') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (1721915,'Сервисмаркет на Бейвеля') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (2066103,'Сервисмаркет на Труда') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (2115264,'Сервисмаркет на Пугачева') RETURNING id;
INSERT INTO service_markets (service_market_id, service_market_name) VALUES (3533882,'Сервисмаркет на Дублере Сибирского тракта') RETURNING id;